/**************************************************************************************************\
 *** 
 *** Simulink model       : powerwindow_tl_v01
 *** TargetLink subsystem : powerwindow_tl_v01/PowerWindow_ClosedLoop/power_window_controller
 *** Codefile             : detect_obstacle_endstop.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-01-20 14:45:06
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : disabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\dspace\TL41\Matlab\Tl\Config\codegen\cconfig.xml
 *** Root style sheet                         : C:\dspace\TL41\Matlab\Tl\XML\CodeGen\Stylesheets\TL_
 ***                                            CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      power_window_controller
 *** Sa2                      power_window_controller/detect_obstacle_endstop
 *** Sa3                      power_window_controller/validate_driver
 *** Sa4                      power_window_controller/validate_passenger
 *** Sa5                      power_window_controller/detect_obstacle_endstop/detect_endstop
 *** Sa6                      power_window_controller/detect_obstacle_endstop/detect_obstacle
 *** Sa7                      power_window_controller/validate_driver/check_down
 *** Sa8                      power_window_controller/validate_driver/check_up
 *** Sa9                      power_window_controller/validate_driver/driver_switch
 *** Sa10                     power_window_controller/validate_driver/mutually_exclusive
 *** Sa11                     power_window_controller/validate_passenger/check_down
 *** Sa12                     power_window_controller/validate_passenger/check_up
 *** Sa13                     power_window_controller/validate_passenger/mutually_exclusive
 *** Sa14                     power_window_controller/validate_passenger/passenger_switch
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** Ca0       powerwindow_tl_v01                                     
 *** Ca1       power_window_controller/control                        
 *** Ca2       power_window_controller/control.safe                   
 *** Ca3       power_window_controller/control.safe.driverNeutral     
 *** Ca4       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerneutral                                          
 *** Ca5       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown                                             
 *** Ca6       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.iniPassengerDown                            
 *** Ca7       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.passengerDown                               
 *** Ca8       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.autoPassengerDown                           
 *** Ca9       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp                                               
 *** Ca10      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.iniPassengerUp                                
 *** Ca11      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.PassengerUp                                   
 *** Ca12      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.autoPassengerUp                               
 *** Ca13      power_window_controller/control.safe.driverUp          
 *** Ca14      power_window_controller/control.safe.driverUp.iniDrive
 ***           rUp                                                    
 *** Ca15      power_window_controller/control.safe.driverUp.DriverUp 
 *** Ca16      power_window_controller/control.safe.driverUp.autoDriv
 ***           erUp                                                   
 *** Ca17      power_window_controller/control.safe.driverDown        
 *** Ca18      power_window_controller/control.safe.driverDown.iniDri
 ***           verDown                                                
 *** Ca19      power_window_controller/control.safe.driverDown.Driver
 ***           Down                                                   
 *** Ca20      power_window_controller/control.safe.driverDown.autoDr
 ***           iverDown                                               
 *** Ca21      power_window_controller/control.emergencyDown          
 *** 
 *** TargetLink version      : 4.1 from 12-Oct-2015
 *** Code generator version  : Build Id 4.1.0.21 from 2015-09-25 11:04:18

\**************************************************************************************************/

#ifndef DETECT_OBSTACLE_ENDSTOP_C
#define DETECT_OBSTACLE_ENDSTOP_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "detect_obstacle_endstop.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 16
\******************************************************************************/
CAL UInt16 Sa5_position_endstop_top = 400 /* 0.4 */ /* 
   Description: position of upper endstop in mm
   LSB: 0.001 OFF:  0 MIN/MAX:  0.35 .. 0.45 */;

/******************************************************************************\
   DISP: global observable variables (RAM) | Width: 8
\******************************************************************************/
DISP Bool detection_endstop_bottom /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
DISP Bool detection_endstop_top /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
DISP Bool detection_obstacle /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool Sa2_endstop_bottom;
Bool Sa2_endstop_top;
Bool Sa2_obstacle;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      detect_obstacle_endstop
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      UInt16             Sa2_obstacle_position
 ***      UInt8              Sa2_window_position 
 ***      Bool               Sa2_move_up         
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void detect_obstacle_endstop(UInt16 Sa2_obstacle_position, UInt8 Sa2_window_position, Bool
  Sa2_move_up)
{
   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/detect_obstacle_endstop/detect_endstop
      /detection_endstop_bottom', ('power_window_controller/detect_obstacle_endstop/detect_endstop/d
      etection_endstop_bottom', ('<=', 'power_window_controller/detect_obstacle_endstop/detect_endst
      op/detection_endstop_bottom', ('power_window_controller/detect_obstacle_endstop/window_positio
      n', 'Source Unknown')))) */
   /* Relational: power_window_controller/detect_obstacle_endstop/detect_endstop/detection_endstop_b
      ottom */
   detection_endstop_bottom = Sa2_window_position <= 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/detect_obstacle_endstop/endstop_bottom
      ', ('power_window_controller/detect_obstacle_endstop/endstop_bottom', 'power_window_controller
      /detect_obstacle_endstop/detect_endstop/detection_endstop_bottom')) */

   /* TargetLink outport: power_window_controller/detect_obstacle_endstop/endstop_bottom */
   Sa2_endstop_bottom = detection_endstop_bottom;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/detect_obstacle_endstop/detect_endstop
      /detection_endstop_top', ('power_window_controller/detect_obstacle_endstop/detect_endstop/dete
      ction_endstop_top', ('>=', 'power_window_controller/detect_obstacle_endstop/detect_endstop/det
      ection_endstop_top', (('(cast)', 'power_window_controller/detect_obstacle_endstop/detect_endst
      op/detection_endstop_top', ('power_window_controller/detect_obstacle_endstop/window_position')
      ), 'power_window_controller/detect_obstacle_endstop/detect_endstop/Constant ')))) */

   /* Relational: power_window_controller/detect_obstacle_endstop/detect_endstop/detection_endstop_t
      op */
   detection_endstop_top = ((UInt16) Sa2_window_position) >= Sa5_position_endstop_top;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/detect_obstacle_endstop/endstop_top', 
      ('power_window_controller/detect_obstacle_endstop/endstop_top', 'power_window_controller/detec
      t_obstacle_endstop/detect_endstop/detection_endstop_top')) */

   /* TargetLink outport: power_window_controller/detect_obstacle_endstop/endstop_top */
   Sa2_endstop_top = detection_endstop_top;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/detect_obstacle_endstop/detect_obstacl
      e/detection_obstacle', ('power_window_controller/detect_obstacle_endstop/detect_obstacle/detec
      tion_obstacle', ('&&', 'power_window_controller/detect_obstacle_endstop/detect_obstacle/detect
      ion_obstacle', (('&&', 'power_window_controller/detect_obstacle_endstop/detect_obstacle/ ', ((
      '>', 'power_window_controller/detect_obstacle_endstop/detect_obstacle/  ', (('(cast)', 'power_
      window_controller/detect_obstacle_endstop/detect_obstacle/  ', ('power_window_controller/detec
      t_obstacle_endstop/window_position')), 'power_window_controller/detect_obstacle_endstop/obstac
      le_position')), ('>', 'power_window_controller/detect_obstacle_endstop/detect_obstacle/   ', (
      'power_window_controller/detect_obstacle_endstop/obstacle_position', 'Source Unknown')))), 'po
      wer_window_controller/detect_obstacle_endstop/move_up')))) */

   /* Logical: power_window_controller/detect_obstacle_endstop/detect_obstacle/detection_obstacle
      # combined # Logical: power_window_controller/detect_obstacle_endstop/detect_obstacle/ 
      # combined # Relational: power_window_controller/detect_obstacle_endstop/detect_obstacle/   
      # combined # Relational: power_window_controller/detect_obstacle_endstop/detect_obstacle/   */
   detection_obstacle = (((UInt16) Sa2_window_position) > Sa2_obstacle_position) &&
    (Sa2_obstacle_position > 0) && Sa2_move_up;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/detect_obstacle_endstop/obstacle', ('p
      ower_window_controller/detect_obstacle_endstop/obstacle', 'power_window_controller/detect_obst
      acle_endstop/detect_obstacle/detection_obstacle')) */

   /* TargetLink outport: power_window_controller/detect_obstacle_endstop/obstacle */
   Sa2_obstacle = detection_obstacle;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif /* DETECT_OBSTACLE_ENDSTOP_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
