/**************************************************************************************************\
 *** 
 *** Simulink model       : powerwindow_tl_v01
 *** TargetLink subsystem : powerwindow_tl_v01/PowerWindow_ClosedLoop/power_window_controller
 *** Codefile             : power_window_controller.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-01-20 14:45:06
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : disabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\dspace\TL41\Matlab\Tl\Config\codegen\cconfig.xml
 *** Root style sheet                         : C:\dspace\TL41\Matlab\Tl\XML\CodeGen\Stylesheets\TL_
 ***                                            CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      power_window_controller
 *** Sa2                      power_window_controller/detect_obstacle_endstop
 *** Sa3                      power_window_controller/validate_driver
 *** Sa4                      power_window_controller/validate_passenger
 *** Sa5                      power_window_controller/detect_obstacle_endstop/detect_endstop
 *** Sa6                      power_window_controller/detect_obstacle_endstop/detect_obstacle
 *** Sa7                      power_window_controller/validate_driver/check_down
 *** Sa8                      power_window_controller/validate_driver/check_up
 *** Sa9                      power_window_controller/validate_driver/driver_switch
 *** Sa10                     power_window_controller/validate_driver/mutually_exclusive
 *** Sa11                     power_window_controller/validate_passenger/check_down
 *** Sa12                     power_window_controller/validate_passenger/check_up
 *** Sa13                     power_window_controller/validate_passenger/mutually_exclusive
 *** Sa14                     power_window_controller/validate_passenger/passenger_switch
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** Ca0       powerwindow_tl_v01                                     
 *** Ca1       power_window_controller/control                        
 *** Ca2       power_window_controller/control.safe                   
 *** Ca3       power_window_controller/control.safe.driverNeutral     
 *** Ca4       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerneutral                                          
 *** Ca5       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown                                             
 *** Ca6       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.iniPassengerDown                            
 *** Ca7       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.passengerDown                               
 *** Ca8       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.autoPassengerDown                           
 *** Ca9       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp                                               
 *** Ca10      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.iniPassengerUp                                
 *** Ca11      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.PassengerUp                                   
 *** Ca12      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.autoPassengerUp                               
 *** Ca13      power_window_controller/control.safe.driverUp          
 *** Ca14      power_window_controller/control.safe.driverUp.iniDrive
 ***           rUp                                                    
 *** Ca15      power_window_controller/control.safe.driverUp.DriverUp 
 *** Ca16      power_window_controller/control.safe.driverUp.autoDriv
 ***           erUp                                                   
 *** Ca17      power_window_controller/control.safe.driverDown        
 *** Ca18      power_window_controller/control.safe.driverDown.iniDri
 ***           verDown                                                
 *** Ca19      power_window_controller/control.safe.driverDown.Driver
 ***           Down                                                   
 *** Ca20      power_window_controller/control.safe.driverDown.autoDr
 ***           iverDown                                               
 *** Ca21      power_window_controller/control.emergencyDown          
 *** 
 *** TargetLink version      : 4.1 from 12-Oct-2015
 *** Code generator version  : Build Id 4.1.0.21 from 2015-09-25 11:04:18

\**************************************************************************************************/

#ifndef POWER_WINDOW_CONTROLLER_C
#define POWER_WINDOW_CONTROLLER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "validate_passenger.h"
#include "validate_driver.h"
#include "power_window_controller.h"
#include "detect_obstacle_endstop.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\******************************************************************************/
CAL UInt8 Sa1_auto_down_time = 100 /* 
   Description: value in 10 ms steps
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
CAL UInt8 Sa1_auto_up_time = 100 /* 
   Description: value in 10 ms steps
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
CAL UInt8 Sa1_emergency_down_time = 100 /* 
   Description: value in 10 ms steps
   LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

/******************************************************************************\
   GLOBAL: global variables (RAM) | Width: 16
\******************************************************************************/
GLOBAL UInt16 Sa1_obstacle_position /* 
   Description: obstacle position in mm
   LSB: 0.001 OFF:  0 MIN/MAX:  0 .. 0.45 */;
GLOBAL UInt16 Sa1_window_position /* 
   Description: window position in mm
   LSB: 0.001 OFF:  0 MIN/MAX:  0 .. 0.45 */;

/******************************************************************************\
   GLOBAL: global variables (RAM) | Width: 8
\******************************************************************************/
GLOBAL Bool Sa1_driver_down /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
GLOBAL Bool Sa1_driver_up /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
GLOBAL Bool Sa1_move_down /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
GLOBAL Bool Sa1_move_up /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
GLOBAL Bool Sa1_obstacle_detection /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
GLOBAL Bool Sa1_passenger_down /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;
GLOBAL Bool Sa1_passenger_up /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */;

/******************************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    8
\******************************************************************************/
static Bool Ca1_moveDown = 0;
static Bool Ca1_moveUp = 0;

/******************************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    N.A.
\******************************************************************************/
static struct tag_SIBFS_control_a_tp SIBFS_control_a = {
   0 /* Ca10_iniPassengerUp: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca11_PassengerUp: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca13_driverUp: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca14_iniDriverUp: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca15_DriverUp: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca17_driverDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca18_iniDriverDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca19_DriverDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca21_emergencyDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca2_safe: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca3_driverNeutral: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca4_passengerneutral: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca5_passengerDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca6_iniPassengerDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca7_passengerDown: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */, 
   0 /* Ca9_passengerUp: LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 1 */
} /* Description: Structure containing bitfields for Stateflow chart  */;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/******************************************************************************\
   StaticSFEntry: Default function class for static stateflow entry functions
\******************************************************************************/
static void Ca4_passengerneutral_en(void);

/******************************************************************************\
   StaticSFExit: Default function class for static stateflow exit functions
\******************************************************************************/
static void Ca3_driverNeutral_ex(void);
static void Ca5_passengerDown_ex(void);
static void Ca9_passengerUp_ex(void);

/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      power_window_controller
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void power_window_controller(void)
{
   /* variable for static local variables with initvalue  | Width: 16
   */
   UInt16 Ca1_obstacle_position = Sa1_obstacle_position;

   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
    */
   static UInt8 Ca1_control_ctr = 0;
   static UInt8 Ca1_control_ctr_a = 0;
   static UInt8 Ca1_control_ctr_b = 0;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
    */
   static Bool X_Sa1_Unit_Delay = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('detect_obstacle_endstop', 'power_window_controller/detect_obstacle_
      endstop/Function', ('power_window_controller/obstacle_position', ('(cast)', 'power_window_cont
      roller/window_position', ('power_window_controller/window_position')), 'power_window_controlle
      r/Unit Delay')) */
   /* call of function: power_window_controller/detect_obstacle_endstop
      # combined # update(s) for inport power_window_controller/detect_obstacle_endstop/window_posit
      ion */
   detect_obstacle_endstop(Sa1_obstacle_position, (UInt8) Sa1_window_position, X_Sa1_Unit_Delay);

   /* TL_AUTO_COMMENT BLOCKREF ('validate_driver', 'power_window_controller/validate_driver/Function
      ', ()) */

   /* call of function: power_window_controller/validate_driver */
   validate_driver();

   /* TL_AUTO_COMMENT BLOCKREF ('validate_passenger', 'power_window_controller/validate_passenger/Fu
      nction', ()) */

   /* call of function: power_window_controller/validate_passenger */
   validate_passenger();

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', (('<', 'power_window_contro
      ller/control', ('power_window_controller/control', 'Source Unknown')))) */
   if (Ca1_control_ctr < 255) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller
         /control', ('+', 'power_window_controller/control', ('power_window_controller/control', 'So
         urce Unknown')))) */
      Ca1_control_ctr = Ca1_control_ctr + 1;
   }

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', (('<', 'power_window_contro
      ller/control', ('power_window_controller/control', 'Source Unknown')))) */
   if (Ca1_control_ctr_a < 255) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller
         /control', ('+', 'power_window_controller/control', ('power_window_controller/control', 'So
         urce Unknown')))) */
      Ca1_control_ctr_a = Ca1_control_ctr_a + 1;
   }

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', (('<', 'power_window_contro
      ller/control', ('power_window_controller/control', 'Source Unknown')))) */
   if (Ca1_control_ctr_b < 255) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller
         /control', ('+', 'power_window_controller/control', ('power_window_controller/control', 'So
         urce Unknown')))) */
      Ca1_control_ctr_b = Ca1_control_ctr_b + 1;
   }

   /* Begin execution of chart power_window_controller/control */

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controller/c
      ontrol')) */
   if (SIBFS_control_a.Ca2_safe) {
      /* Begin execution of state power_window_controller/control.safe */
      if (SIBFS_control_a.Ca3_driverNeutral) {
         /* Begin execution of state power_window_controller/control.safe.driverNeutral */

         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_contro
            ller/detect_obstacle_endstop/obstacle')) */
         if (Sa2_obstacle) {
            /* State transition from power_window_controller/control.safe.driverNeutral to power_win
               dow_controller/control.emergencyDown */

            /* TL_AUTO_COMMENT BLOCKREF ('Ca3_driverNeutral_ex', 'power_window_controller/control', 
               ()) */
            Ca3_driverNeutral_ex();

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_cont
               roller/control', 'Source Unknown')) */
            SIBFS_control_a.Ca2_safe = 0;
            Ca1_control_ctr = 0;
            SIBFS_control_a.Ca21_emergencyDown = 1;

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_cont
               roller/control.moveUp', 'Source Unknown')) */
            Ca1_moveUp = 0;

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_cont
               roller/control.moveDown', 'Source Unknown')) */
            Ca1_moveDown = 1;
         }
         else {
            /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_con
               troller/validate_driver/validated_up')) */
            if (Sa3_validated_up) {
               /* State transition from power_window_controller/control.safe.driverNeutral to power_
                  window_controller/control.safe.driverUp.iniDriverUp */

               /* TL_AUTO_COMMENT BLOCKREF ('Ca3_driverNeutral_ex', 'power_window_controller/control
                  ', ()) */
               Ca3_driverNeutral_ex();

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control', 'Source Unknown')) */
               SIBFS_control_a.Ca13_driverUp = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control.moveUp', 'Source Unknown')) */
               Ca1_moveUp = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control', 'Source Unknown')) */
               Ca1_control_ctr_b = 0;
               SIBFS_control_a.Ca14_iniDriverUp = 1;
            }
            else {
               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_
                  controller/validate_driver/validated_down')) */
               if (Sa3_validated_down) {
                  /* State transition from power_window_controller/control.safe.driverNeutral to pow
                     er_window_controller/control.safe.driverDown.iniDriverDown */

                  /* TL_AUTO_COMMENT BLOCKREF ('Ca3_driverNeutral_ex', 'power_window_controller/cont
                     rol', ()) */
                  Ca3_driverNeutral_ex();

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  SIBFS_control_a.Ca17_driverDown = 1;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control.moveDown', 'Source Unknown')) */
                  Ca1_moveDown = 1;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  Ca1_control_ctr_b = 0;
                  SIBFS_control_a.Ca18_iniDriverDown = 1;
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_wind
                     ow_controller/control')) */
                  if (SIBFS_control_a.Ca4_passengerneutral) {
                     /* Begin execution of state power_window_controller/control.safe.driverNeutral.
                        passengerneutral */

                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/validate_passenger/validated_up')) */
                     if (Sa4_validated_up) {
                        /* State transition from power_window_controller/control.safe.driverNeutral.
                           passengerneutral to power_window_controller/control.safe.driverNeutral.pa
                           ssengerUp.iniPassengerUp */

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control', 'Source Unknown')) */
                        SIBFS_control_a.Ca4_passengerneutral = 0;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control', 'Source Unknown')) */
                        SIBFS_control_a.Ca9_passengerUp = 1;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control.moveUp', 'Source Unknown')) */
                        Ca1_moveUp = 1;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control', 'Source Unknown')) */
                        Ca1_control_ctr_a = 0;
                        SIBFS_control_a.Ca10_iniPassengerUp = 1;
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/validate_passenger/validated_down')) */
                        if (Sa4_validated_down) {
                           /* State transition from power_window_controller/control.safe.driverNeutr
                              al.passengerneutral to power_window_controller/control.safe.driverNeut
                              ral.passengerDown.iniPassengerDown */

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca4_passengerneutral = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca5_passengerDown = 1;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control.moveDown', 'Source Unknown')) */
                           Ca1_moveDown = 1;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           Ca1_control_ctr_a = 0;
                           SIBFS_control_a.Ca6_iniPassengerDown = 1;
                        }
                     }

                     /* End execution of state power_window_controller/control.safe.driverNeutral.pa
                        ssengerneutral */
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/control')) */
                     if (SIBFS_control_a.Ca5_passengerDown) {
                        /* Begin execution of state power_window_controller/control.safe.driverNeutr
                           al.passengerDown */

                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/detect_obstacle_endstop/endstop_bottom')) */
                        if (Sa2_endstop_bottom) {
                           /* State transition from power_window_controller/control.safe.driverNeutr
                              al.passengerDown to power_window_controller/control.safe.driverNeutral
                              .passengerneutral */

                           /* TL_AUTO_COMMENT BLOCKREF ('Ca5_passengerDown_ex', 'power_window_contro
                              ller/control', ()) */
                           Ca5_passengerDown_ex();

                           /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_con
                              troller/control', ()) */
                           Ca4_passengerneutral_en();
                        }
                        else {
                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('p
                              ower_window_controller/validate_passenger/validated_up')) */
                           if (Sa4_validated_up) {
                              /* State transition from power_window_controller/control.safe.driverNe
                                 utral.passengerDown to power_window_controller/control.safe.driverN
                                 eutral.passengerUp.PassengerUp */

                              /* TL_AUTO_COMMENT BLOCKREF ('Ca5_passengerDown_ex', 'power_window_con
                                 troller/control', ()) */
                              Ca5_passengerDown_ex();

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca9_passengerUp = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control.moveUp', 'Source Unknown')) */
                              Ca1_moveUp = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca11_PassengerUp = 1;
                           }
                           else {
                              /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', 
                                 ('power_window_controller/control')) */
                              if (SIBFS_control_a.Ca6_iniPassengerDown) {
                                 /* Begin execution of state power_window_controller/control.safe.dr
                                    iverNeutral.passengerDown.iniPassengerDown */

                                 /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control
                                    ', (('>=', 'power_window_controller/control', ('power_window_con
                                    troller/control', 'power_window_controller/Constant1')))) */
                                 if (Ca1_control_ctr_a >= Sa1_auto_down_time) {
                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/cont
                                       rol', ('power_window_controller/validate_passenger/validated_
                                       neutral')) */
                                    if (Sa4_validated_neutral) {
                                       /* State transition to power_window_controller/control.safe.d
                                          riverNeutral.passengerDown.autoPassengerDown */

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/co
                                          ntrol', ('power_window_controller/control', 'Source Unknow
                                          n')) */
                                       SIBFS_control_a.Ca6_iniPassengerDown = 0;
                                    }
                                    else {
                                       /* State transition to power_window_controller/control.safe.d
                                          riverNeutral.passengerDown.passengerDown */
                                       SIBFS_control_a.Ca6_iniPassengerDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/co
                                          ntrol', ('power_window_controller/control', 'Source Unknow
                                          n')) */
                                       SIBFS_control_a.Ca7_passengerDown = 1;
                                    }
                                 }

                                 /* End execution of state power_window_controller/control.safe.driv
                                    erNeutral.passengerDown.iniPassengerDown */
                              }
                              else {
                                 /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control
                                    ', ('power_window_controller/control')) */
                                 if (SIBFS_control_a.Ca7_passengerDown) {
                                    /* Begin execution of state power_window_controller/control.safe
                                       .driverNeutral.passengerDown.passengerDown */

                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/cont
                                       rol', ('power_window_controller/validate_passenger/validated_
                                       neutral')) */
                                    if (Sa4_validated_neutral) {
                                       /* State transition from power_window_controller/control.safe
                                          .driverNeutral.passengerDown.passengerDown to power_window
                                          _controller/control.safe.driverNeutral.passengerneutral */

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/co
                                          ntrol', ('power_window_controller/control', 'Source Unknow
                                          n')) */
                                       SIBFS_control_a.Ca7_passengerDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/co
                                          ntrol', ('power_window_controller/control.moveDown', 'Sour
                                          ce Unknown')) */
                                       Ca1_moveDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/co
                                          ntrol', ('power_window_controller/control', 'Source Unknow
                                          n')) */
                                       SIBFS_control_a.Ca5_passengerDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'powe
                                          r_window_controller/control', ()) */
                                       Ca4_passengerneutral_en();
                                    }

                                    /* End execution of state power_window_controller/control.safe.d
                                       riverNeutral.passengerDown.passengerDown */
                                 }
                              }
                           }
                        }

                        /* End execution of state power_window_controller/control.safe.driverNeutral
                           .passengerDown */
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/control')) */
                        if (SIBFS_control_a.Ca9_passengerUp) {
                           /* Begin execution of state power_window_controller/control.safe.driverNe
                              utral.passengerUp */

                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('p
                              ower_window_controller/validate_passenger/validated_down')) */
                           if (Sa4_validated_down) {
                              /* State transition from power_window_controller/control.safe.driverNe
                                 utral.passengerUp to power_window_controller/control.safe.driverNeu
                                 tral.passengerDown.passengerDown */

                              /* TL_AUTO_COMMENT BLOCKREF ('Ca9_passengerUp_ex', 'power_window_contr
                                 oller/control', ()) */
                              Ca9_passengerUp_ex();

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca5_passengerDown = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control.moveDown', 'Source Unknown')) */
                              Ca1_moveDown = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca7_passengerDown = 1;
                           }
                           else {
                              /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', 
                                 ('power_window_controller/detect_obstacle_endstop/endstop_top')) */
                              if (Sa2_endstop_top) {
                                 /* State transition from power_window_controller/control.safe.drive
                                    rNeutral.passengerUp to power_window_controller/control.safe.dri
                                    verNeutral.passengerneutral */

                                 /* TL_AUTO_COMMENT BLOCKREF ('Ca9_passengerUp_ex', 'power_window_co
                                    ntroller/control', ()) */
                                 Ca9_passengerUp_ex();

                                 /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_wind
                                    ow_controller/control', ()) */
                                 Ca4_passengerneutral_en();
                              }
                              else {
                                 /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control
                                    ', ('power_window_controller/control')) */
                                 if (SIBFS_control_a.Ca10_iniPassengerUp) {
                                    /* Begin execution of state power_window_controller/control.safe
                                       .driverNeutral.passengerUp.iniPassengerUp */

                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/cont
                                       rol', (('>=', 'power_window_controller/control', ('power_wind
                                       ow_controller/control', 'power_window_controller/Constant2'))
                                       )) */
                                    if (Ca1_control_ctr_a >= Sa1_auto_up_time) {
                                       /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/c
                                          ontrol', ('power_window_controller/validate_passenger/vali
                                          dated_neutral')) */
                                       if (Sa4_validated_neutral) {
                                          /* State transition to power_window_controller/control.saf
                                          e.driverNeutral.passengerUp.autoPassengerUp */

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          /control', ('power_window_controller/control', 'Source 
                                          Unknown')) */
                                          SIBFS_control_a.Ca10_iniPassengerUp = 0;
                                       }
                                       else {
                                          /* State transition to power_window_controller/control.saf
                                          e.driverNeutral.passengerUp.PassengerUp */
                                          SIBFS_control_a.Ca10_iniPassengerUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          /control', ('power_window_controller/control', 'Source 
                                          Unknown')) */
                                          SIBFS_control_a.Ca11_PassengerUp = 1;
                                       }
                                    }

                                    /* End execution of state power_window_controller/control.safe.d
                                       riverNeutral.passengerUp.iniPassengerUp */
                                 }
                                 else {
                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/cont
                                       rol', ('power_window_controller/control')) */
                                    if (SIBFS_control_a.Ca11_PassengerUp) {
                                       /* Begin execution of state power_window_controller/control.s
                                          afe.driverNeutral.passengerUp.PassengerUp */

                                       /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/c
                                          ontrol', ('power_window_controller/validate_passenger/vali
                                          dated_neutral')) */
                                       if (Sa4_validated_neutral) {
                                          /* State transition from power_window_controller/control.s
                                          afe.driverNeutral.passengerUp.PassengerUp to power_wind
                                          ow_controller/control.safe.driverNeutral.passengerneutr
                                          al */

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          /control', ('power_window_controller/control', 'Source 
                                          Unknown')) */
                                          SIBFS_control_a.Ca11_PassengerUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          /control', ('power_window_controller/control.moveUp', '
                                          Source Unknown')) */
                                          Ca1_moveUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          /control', ('power_window_controller/control', 'Source 
                                          Unknown')) */
                                          SIBFS_control_a.Ca9_passengerUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'p
                                          ower_window_controller/control', ()) */
                                          Ca4_passengerneutral_en();
                                       }

                                       /* End execution of state power_window_controller/control.saf
                                          e.driverNeutral.passengerUp.PassengerUp */
                                    }
                                 }
                              }
                           }

                           /* End execution of state power_window_controller/control.safe.driverNeut
                              ral.passengerUp */
                        }
                     }
                  }
               }
            }
         }

         /* End execution of state power_window_controller/control.safe.driverNeutral */
      }
      else {
         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_contro
            ller/control')) */
         if (SIBFS_control_a.Ca13_driverUp) {
            /* Begin execution of state power_window_controller/control.safe.driverUp */

            /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_con
               troller/validate_driver/validated_down')) */
            if (Sa3_validated_down) {
               /* State transition from power_window_controller/control.safe.driverUp to power_windo
                  w_controller/control.safe.driverDown.DriverDown */

               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_
                  controller/control')) */
               if (SIBFS_control_a.Ca14_iniDriverUp) {
                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  SIBFS_control_a.Ca14_iniDriverUp = 0;
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_wind
                     ow_controller/control')) */
                  if (SIBFS_control_a.Ca15_DriverUp) {
                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control', 'Source Unknown')) */
                     SIBFS_control_a.Ca15_DriverUp = 0;
                  }
               }

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control.moveUp', 'Source Unknown')) */
               Ca1_moveUp = 0;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control', 'Source Unknown')) */
               SIBFS_control_a.Ca13_driverUp = 0;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control', 'Source Unknown')) */
               SIBFS_control_a.Ca17_driverDown = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control.moveDown', 'Source Unknown')) */
               Ca1_moveDown = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_c
                  ontroller/control', 'Source Unknown')) */
               SIBFS_control_a.Ca19_DriverDown = 1;
            }
            else {
               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_
                  controller/detect_obstacle_endstop/endstop_top')) */
               if (Sa2_endstop_top) {
                  /* State transition from power_window_controller/control.safe.driverUp to power_wi
                     ndow_controller/control.safe.driverNeutral */

                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_wind
                     ow_controller/control')) */
                  if (SIBFS_control_a.Ca14_iniDriverUp) {
                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control', 'Source Unknown')) */
                     SIBFS_control_a.Ca14_iniDriverUp = 0;
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/control')) */
                     if (SIBFS_control_a.Ca15_DriverUp) {
                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control', 'Source Unknown')) */
                        SIBFS_control_a.Ca15_DriverUp = 0;
                     }
                  }

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control.moveUp', 'Source Unknown')) */
                  Ca1_moveUp = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  SIBFS_control_a.Ca13_driverUp = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  SIBFS_control_a.Ca3_driverNeutral = 1;

                  /* State transition to power_window_controller/control.safe.driverNeutral.passenge
                     rneutral */

                  /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller/c
                     ontrol', ()) */
                  Ca4_passengerneutral_en();
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_wind
                     ow_controller/control')) */
                  if (SIBFS_control_a.Ca14_iniDriverUp) {
                     /* Begin execution of state power_window_controller/control.safe.driverUp.iniDr
                        iverUp */

                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', (('>=', '
                        power_window_controller/control', ('power_window_controller/control', 'power
                        _window_controller/Constant2')))) */
                     if (Ca1_control_ctr_b >= Sa1_auto_up_time) {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/validate_driver/validated_neutral')) */
                        if (Sa3_validated_neutral) {
                           /* State transition to power_window_controller/control.safe.driverUp.auto
                              DriverUp */

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca14_iniDriverUp = 0;
                        }
                        else {
                           /* State transition to power_window_controller/control.safe.driverUp.Driv
                              erUp */
                           SIBFS_control_a.Ca14_iniDriverUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca15_DriverUp = 1;
                        }
                     }

                     /* End execution of state power_window_controller/control.safe.driverUp.iniDriv
                        erUp */
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/control')) */
                     if (SIBFS_control_a.Ca15_DriverUp) {
                        /* Begin execution of state power_window_controller/control.safe.driverUp.Dr
                           iverUp */

                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/validate_driver/validated_neutral')) */
                        if (Sa3_validated_neutral) {
                           /* State transition from power_window_controller/control.safe.driverUp.Dr
                              iverUp to power_window_controller/control.safe.driverNeutral */

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca15_DriverUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control.moveUp', 'Source Unknown')) */
                           Ca1_moveUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca13_driverUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca3_driverNeutral = 1;

                           /* State transition to power_window_controller/control.safe.driverNeutral
                              .passengerneutral */

                           /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_con
                              troller/control', ()) */
                           Ca4_passengerneutral_en();
                        }

                        /* End execution of state power_window_controller/control.safe.driverUp.Driv
                           erUp */
                     }
                  }
               }
            }

            /* End execution of state power_window_controller/control.safe.driverUp */
         }
         else {
            /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_con
               troller/control')) */
            if (SIBFS_control_a.Ca17_driverDown) {
               /* Begin execution of state power_window_controller/control.safe.driverDown */

               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_
                  controller/detect_obstacle_endstop/endstop_bottom')) */
               if (Sa2_endstop_bottom) {
                  /* State transition from power_window_controller/control.safe.driverDown to power_
                     window_controller/control.safe.driverNeutral */

                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_wind
                     ow_controller/control')) */
                  if (SIBFS_control_a.Ca18_iniDriverDown) {
                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control', 'Source Unknown')) */
                     SIBFS_control_a.Ca18_iniDriverDown = 0;
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/control')) */
                     if (SIBFS_control_a.Ca19_DriverDown) {
                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control', 'Source Unknown')) */
                        SIBFS_control_a.Ca19_DriverDown = 0;
                     }
                  }

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control.moveDown', 'Source Unknown')) */
                  Ca1_moveDown = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  SIBFS_control_a.Ca17_driverDown = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_windo
                     w_controller/control', 'Source Unknown')) */
                  SIBFS_control_a.Ca3_driverNeutral = 1;

                  /* State transition to power_window_controller/control.safe.driverNeutral.passenge
                     rneutral */

                  /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller/c
                     ontrol', ()) */
                  Ca4_passengerneutral_en();
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_wind
                     ow_controller/validate_driver/validated_up')) */
                  if (Sa3_validated_up) {
                     /* State transition from power_window_controller/control.safe.driverDown to pow
                        er_window_controller/control.safe.driverUp.DriverUp */

                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/control')) */
                     if (SIBFS_control_a.Ca18_iniDriverDown) {
                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power
                           _window_controller/control', 'Source Unknown')) */
                        SIBFS_control_a.Ca18_iniDriverDown = 0;
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/control')) */
                        if (SIBFS_control_a.Ca19_DriverDown) {
                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('po
                              wer_window_controller/control', 'Source Unknown')) */
                           SIBFS_control_a.Ca19_DriverDown = 0;
                        }
                     }

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control.moveDown', 'Source Unknown')) */
                     Ca1_moveDown = 0;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control', 'Source Unknown')) */
                     SIBFS_control_a.Ca17_driverDown = 0;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control', 'Source Unknown')) */
                     SIBFS_control_a.Ca13_driverUp = 1;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control.moveUp', 'Source Unknown')) */
                     Ca1_moveUp = 1;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_wi
                        ndow_controller/control', 'Source Unknown')) */
                     SIBFS_control_a.Ca15_DriverUp = 1;
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_w
                        indow_controller/control')) */
                     if (SIBFS_control_a.Ca18_iniDriverDown) {
                        /* Begin execution of state power_window_controller/control.safe.driverDown.
                           iniDriverDown */

                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', (('>='
                           , 'power_window_controller/control', ('power_window_controller/control', 
                           'power_window_controller/Constant1')))) */
                        if (Ca1_control_ctr_b >= Sa1_auto_down_time) {
                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('p
                              ower_window_controller/validate_driver/validated_neutral')) */
                           if (Sa3_validated_neutral) {
                              /* State transition to power_window_controller/control.safe.driverDown
                                 .autoDriverDown */

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca18_iniDriverDown = 0;
                           }
                           else {
                              /* State transition to power_window_controller/control.safe.driverDown
                                 .DriverDown */
                              SIBFS_control_a.Ca18_iniDriverDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca19_DriverDown = 1;
                           }
                        }

                        /* End execution of state power_window_controller/control.safe.driverDown.in
                           iDriverDown */
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('powe
                           r_window_controller/control')) */
                        if (SIBFS_control_a.Ca19_DriverDown) {
                           /* Begin execution of state power_window_controller/control.safe.driverDo
                              wn.DriverDown */

                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('p
                              ower_window_controller/validate_driver/validated_neutral')) */
                           if (Sa3_validated_neutral) {
                              /* State transition from power_window_controller/control.safe.driverDo
                                 wn.DriverDown to power_window_controller/control.safe.driverNeutral
                               */

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca19_DriverDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control.moveDown', 'Source Unknown')) */
                              Ca1_moveDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca17_driverDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', (
                                 'power_window_controller/control', 'Source Unknown')) */
                              SIBFS_control_a.Ca3_driverNeutral = 1;

                              /* State transition to power_window_controller/control.safe.driverNeut
                                 ral.passengerneutral */

                              /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_
                                 controller/control', ()) */
                              Ca4_passengerneutral_en();
                           }

                           /* End execution of state power_window_controller/control.safe.driverDown
                              .DriverDown */
                        }
                     }
                  }
               }

               /* End execution of state power_window_controller/control.safe.driverDown */
            }
         }
      }

      /* End execution of state power_window_controller/control.safe */
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controlle
         r/control')) */
      if (SIBFS_control_a.Ca21_emergencyDown) {
         /* Begin execution of state power_window_controller/control.emergencyDown */

         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', (('||', 'power_window
            _controller/control', ('power_window_controller/detect_obstacle_endstop/endstop_bottom',
             ('>=', 'power_window_controller/control', ('power_window_controller/control', 'power_wi
            ndow_controller/Constant')))))) */
         if (Sa2_endstop_bottom || (Ca1_control_ctr >= Sa1_emergency_down_time)) {
            /* State transition from power_window_controller/control.emergencyDown to power_window_c
               ontroller/control.safe.driverNeutral.passengerneutral */

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_cont
               roller/control', 'Source Unknown')) */
            SIBFS_control_a.Ca21_emergencyDown = 0;
            SIBFS_control_a.Ca2_safe = 1;
            SIBFS_control_a.Ca3_driverNeutral = 1;

            /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller/control
               ', ()) */
            Ca4_passengerneutral_en();
         }

         /* End execution of state power_window_controller/control.emergencyDown */
      }
      else {
         /* State transition to power_window_controller/control.safe */

         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_control
            ler/control', 'Source Unknown')) */
         SIBFS_control_a.Ca2_safe = 1;

         /* State transition to power_window_controller/control.safe.driverNeutral */

         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_control
            ler/control', 'Source Unknown')) */
         SIBFS_control_a.Ca3_driverNeutral = 1;

         /* State transition to power_window_controller/control.safe.driverNeutral.passengerneutral
          */

         /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller/control', 
            ()) */
         Ca4_passengerneutral_en();
      }
   }

   /* End execution of chart power_window_controller/control */

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/Unit Delay', ('power_window_controller
      /Unit Delay', 'power_window_controller/control.moveUp')) */

   /* Unit delay: power_window_controller/Unit Delay */
   X_Sa1_Unit_Delay = Ca1_moveUp;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/move_down', ('power_window_controller/
      move_down', 'power_window_controller/control.moveDown')) */

   /* TargetLink outport: power_window_controller/move_down */
   Sa1_move_down = Ca1_moveDown;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/move_up', ('power_window_controller/mo
      ve_up', 'power_window_controller/control.moveUp')) */

   /* TargetLink outport: power_window_controller/move_up */
   Sa1_move_up = Ca1_moveUp;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/obstacle_detection', ('power_window_co
      ntroller/obstacle_detection', 'power_window_controller/detect_obstacle_endstop/obstacle')) */

   /* TargetLink outport: power_window_controller/obstacle_detection */
   Sa1_obstacle_detection = Sa2_obstacle;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca4_passengerneutral_en
 *** 
 ***  DESCRIPTION:
 ***      Entry function of state: power_window_controller/control.safe.driverNeutral.passengerneutr
 ***      al
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca4_passengerneutral_en(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol', 'Source Unknown')) */
   SIBFS_control_a.Ca4_passengerneutral = 1;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol.moveUp', 'Source Unknown')) */
   Ca1_moveUp = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol.moveDown', 'Source Unknown')) */
   Ca1_moveDown = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca3_driverNeutral_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: power_window_controller/control.safe.driverNeutral
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca3_driverNeutral_ex(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controller/c
      ontrol')) */
   if (SIBFS_control_a.Ca4_passengerneutral) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller
         /control', 'Source Unknown')) */
      SIBFS_control_a.Ca4_passengerneutral = 0;
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controlle
         r/control')) */
      if (SIBFS_control_a.Ca5_passengerDown) {
         /* TL_AUTO_COMMENT BLOCKREF ('Ca5_passengerDown_ex', 'power_window_controller/control', ())
          */
         Ca5_passengerDown_ex();
      }
      else {
         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_contro
            ller/control')) */
         if (SIBFS_control_a.Ca9_passengerUp) {
            /* TL_AUTO_COMMENT BLOCKREF ('Ca9_passengerUp_ex', 'power_window_controller/control', ()
               ) */
            Ca9_passengerUp_ex();
         }
      }
   }

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol', 'Source Unknown')) */
   SIBFS_control_a.Ca3_driverNeutral = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca5_passengerDown_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: power_window_controller/control.safe.driverNeutral.passengerDown
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca5_passengerDown_ex(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controller/c
      ontrol')) */
   if (SIBFS_control_a.Ca6_iniPassengerDown) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller
         /control', 'Source Unknown')) */
      SIBFS_control_a.Ca6_iniPassengerDown = 0;
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controlle
         r/control')) */
      if (SIBFS_control_a.Ca7_passengerDown) {
         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_control
            ler/control', 'Source Unknown')) */
         SIBFS_control_a.Ca7_passengerDown = 0;
      }
   }

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol.moveDown', 'Source Unknown')) */
   Ca1_moveDown = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol', 'Source Unknown')) */
   SIBFS_control_a.Ca5_passengerDown = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca9_passengerUp_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: power_window_controller/control.safe.driverNeutral.passengerUp
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca9_passengerUp_ex(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controller/c
      ontrol')) */
   if (SIBFS_control_a.Ca10_iniPassengerUp) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller
         /control', 'Source Unknown')) */
      SIBFS_control_a.Ca10_iniPassengerUp = 0;
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller/control', ('power_window_controlle
         r/control')) */
      if (SIBFS_control_a.Ca11_PassengerUp) {
         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_control
            ler/control', 'Source Unknown')) */
         SIBFS_control_a.Ca11_PassengerUp = 0;
      }
   }

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol.moveUp', 'Source Unknown')) */
   Ca1_moveUp = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/control', ('power_window_controller/co
      ntrol', 'Source Unknown')) */
   SIBFS_control_a.Ca9_passengerUp = 0;
}


#endif /* POWER_WINDOW_CONTROLLER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
