/**************************************************************************************************\
 *** 
 *** Simulink model       : powerwindow_tl_v01
 *** TargetLink subsystem : powerwindow_tl_v01/PowerWindow_ClosedLoop/power_window_controller
 *** Codefile             : validate_driver.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2017-01-20 14:45:06
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : disabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\dspace\TL41\Matlab\Tl\Config\codegen\cconfig.xml
 *** Root style sheet                         : C:\dspace\TL41\Matlab\Tl\XML\CodeGen\Stylesheets\TL_
 ***                                            CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1                      power_window_controller
 *** Sa2                      power_window_controller/detect_obstacle_endstop
 *** Sa3                      power_window_controller/validate_driver
 *** Sa4                      power_window_controller/validate_passenger
 *** Sa5                      power_window_controller/detect_obstacle_endstop/detect_endstop
 *** Sa6                      power_window_controller/detect_obstacle_endstop/detect_obstacle
 *** Sa7                      power_window_controller/validate_driver/check_down
 *** Sa8                      power_window_controller/validate_driver/check_up
 *** Sa9                      power_window_controller/validate_driver/driver_switch
 *** Sa10                     power_window_controller/validate_driver/mutually_exclusive
 *** Sa11                     power_window_controller/validate_passenger/check_down
 *** Sa12                     power_window_controller/validate_passenger/check_up
 *** Sa13                     power_window_controller/validate_passenger/mutually_exclusive
 *** Sa14                     power_window_controller/validate_passenger/passenger_switch
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** Ca0       powerwindow_tl_v01                                     
 *** Ca1       power_window_controller/control                        
 *** Ca2       power_window_controller/control.safe                   
 *** Ca3       power_window_controller/control.safe.driverNeutral     
 *** Ca4       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerneutral                                          
 *** Ca5       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown                                             
 *** Ca6       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.iniPassengerDown                            
 *** Ca7       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.passengerDown                               
 *** Ca8       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerDown.autoPassengerDown                           
 *** Ca9       power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp                                               
 *** Ca10      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.iniPassengerUp                                
 *** Ca11      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.PassengerUp                                   
 *** Ca12      power_window_controller/control.safe.driverNeutral.pas
 ***           sengerUp.autoPassengerUp                               
 *** Ca13      power_window_controller/control.safe.driverUp          
 *** Ca14      power_window_controller/control.safe.driverUp.iniDrive
 ***           rUp                                                    
 *** Ca15      power_window_controller/control.safe.driverUp.DriverUp 
 *** Ca16      power_window_controller/control.safe.driverUp.autoDriv
 ***           erUp                                                   
 *** Ca17      power_window_controller/control.safe.driverDown        
 *** Ca18      power_window_controller/control.safe.driverDown.iniDri
 ***           verDown                                                
 *** Ca19      power_window_controller/control.safe.driverDown.Driver
 ***           Down                                                   
 *** Ca20      power_window_controller/control.safe.driverDown.autoDr
 ***           iverDown                                               
 *** Ca21      power_window_controller/control.emergencyDown          
 *** 
 *** TargetLink version      : 4.1 from 12-Oct-2015
 *** Code generator version  : Build Id 4.1.0.21 from 2015-09-25 11:04:18

\**************************************************************************************************/

#ifndef VALIDATE_DRIVER_C
#define VALIDATE_DRIVER_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/
#include "validate_driver.h"
#include "power_window_controller.h"
#include "detect_obstacle_endstop.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
Bool Sa3_validated_down;
Bool Sa3_validated_neutral;
Bool Sa3_validated_up;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      validate_driver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void validate_driver(void)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   Bool Sa10_up_after_down;
   Bool Sa7_Logical_Operator;
   Bool Sa8_allow_action;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/validate_driver/check_down/Logical Ope
      rator', ('power_window_controller/validate_driver/check_down/Logical Operator', ('&&', 'power_
      window_controller/validate_driver/check_down/Logical Operator', ('power_window_controller/driv
      er_down', ('!', 'power_window_controller/validate_driver/check_down/Logical Operator1', ('powe
      r_window_controller/detect_obstacle_endstop/endstop_bottom')))))) */
   /* Logical: power_window_controller/validate_driver/check_down/Logical Operator
      # combined # Logical: power_window_controller/validate_driver/check_down/Logical Operator1
      # combined # power_window_controller/validate_driver/driver_switch/control input3 */
   Sa7_Logical_Operator = Sa1_driver_down && (!(Sa2_endstop_bottom));

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/validate_driver/validated_down', ('pow
      er_window_controller/validate_driver/validated_down', ('!=', 'power_window_controller/validate
      _driver/validated_down', (('(cast)', 'power_window_controller/validate_driver/check_down/Logic
      al Operator', ('power_window_controller/validate_driver/check_down/Logical Operator')), 'power
      _window_controller/validate_driver/validated_down')))) */

   /* TargetLink outport: power_window_controller/validate_driver/validated_down
      # combined # power_window_controller/validate_driver/mutually_exclusive/validated_down */
   Sa3_validated_down = ((UInt8) Sa7_Logical_Operator) != 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/validate_driver/check_up/allow_action'
      , ('power_window_controller/validate_driver/check_up/allow_action', ('&&', 'power_window_contr
      oller/validate_driver/check_up/allow_action', ('power_window_controller/driver_up', ('!', 'pow
      er_window_controller/validate_driver/check_up/not', ('power_window_controller/detect_obstacle_
      endstop/endstop_top')))))) */

   /* Logical: power_window_controller/validate_driver/check_up/allow_action
      # combined # Logical: power_window_controller/validate_driver/check_up/not
      # combined # power_window_controller/validate_driver/driver_switch/control input2 */
   Sa8_allow_action = Sa1_driver_up && (!(Sa2_endstop_top));

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/validate_driver/mutually_exclusive/up_
      after_down', ('power_window_controller/validate_driver/mutually_exclusive/up_after_down', ('&&
      ', 'power_window_controller/validate_driver/mutually_exclusive/up_after_down', ('power_window_
      controller/validate_driver/check_up/allow_action', ('!', 'power_window_controller/validate_dri
      ver/mutually_exclusive/not_down', ('power_window_controller/validate_driver/check_down/Logical
       Operator')))))) */

   /* Logical: power_window_controller/validate_driver/mutually_exclusive/up_after_down
      # combined # Logical: power_window_controller/validate_driver/mutually_exclusive/not_down */
   Sa10_up_after_down = Sa8_allow_action && (!(Sa7_Logical_Operator));

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/validate_driver/validated_up', ('power
      _window_controller/validate_driver/validated_up', ('!=', 'power_window_controller/validate_dri
      ver/validated_up', (('(cast)', 'power_window_controller/validate_driver/mutually_exclusive/up_
      after_down', ('power_window_controller/validate_driver/mutually_exclusive/up_after_down')), 'p
      ower_window_controller/validate_driver/validated_up')))) */

   /* TargetLink outport: power_window_controller/validate_driver/validated_up
      # combined # power_window_controller/validate_driver/mutually_exclusive/validated_up */
   Sa3_validated_up = ((UInt8) Sa10_up_after_down) != 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller/validate_driver/validated_neutral', ('
      power_window_controller/validate_driver/validated_neutral', ('!=', 'power_window_controller/va
      lidate_driver/validated_neutral', (('(cast)', 'power_window_controller/validate_driver/mutuall
      y_exclusive/default_neutral', (('||', 'power_window_controller/validate_driver/mutually_exclus
      ive/default_neutral', (('&&', 'power_window_controller/validate_driver/mutually_exclusive/neut
      ral_after_up', (('&&', 'power_window_controller/validate_driver/driver_switch/Logical Operator
      1', (('!', 'power_window_controller/validate_driver/driver_switch/control input2', ('power_win
      dow_controller/driver_up')), ('!', 'power_window_controller/validate_driver/driver_switch/cont
      rol input3', ('power_window_controller/driver_down')))), ('!', 'power_window_controller/valida
      te_driver/mutually_exclusive/not_up', ('power_window_controller/validate_driver/mutually_exclu
      sive/up_after_down')))), ('&&', 'power_window_controller/validate_driver/mutually_exclusive/no
      t_up1', (('!', 'power_window_controller/validate_driver/check_up/allow_action', ('power_window
      _controller/validate_driver/check_up/allow_action')), ('!', 'power_window_controller/validate_
      driver/check_down/Logical Operator', ('power_window_controller/validate_driver/check_down/Logi
      cal Operator')))))))), 'power_window_controller/validate_driver/validated_neutral')))) */

   /* TargetLink outport: power_window_controller/validate_driver/validated_neutral
      # combined # power_window_controller/validate_driver/mutually_exclusive/validated_neutral
      # combined # Logical: power_window_controller/validate_driver/mutually_exclusive/default_neutr
      al
      # combined # Logical: power_window_controller/validate_driver/mutually_exclusive/not_up1
      # combined # Logical: power_window_controller/validate_driver/mutually_exclusive/neutral_after
      _up
      # combined # Logical: power_window_controller/validate_driver/mutually_exclusive/not_up
      # combined # Logical: power_window_controller/validate_driver/driver_switch/Logical Operator1
    */
   Sa3_validated_neutral = ((UInt8) (((!(Sa1_driver_up)) && (!(Sa1_driver_down)) &&
    (!(Sa10_up_after_down))) || ((!(Sa8_allow_action)) && (!(Sa7_Logical_Operator))))) != 0;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#endif /* VALIDATE_DRIVER_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
